### ISSUE TITLE
method missing with spaCy 3.7.0

### ISSUE THREAD

**Issue by mscrivo** [yohasebe/ruby-spacy#5]
spaCy 3.7.0 was just released and we started seeing these errors in our builds when using it:

```
/home/repo/vendor/bundle/ruby/3.2.0/gems/pycall-1.4.2/lib/pycall/pyobject_wrapper.rb:52:in `method_missing': undefined method `displacy' for <module 'spacy' from '/opt/venv/lib/python3.11/site-packages/spacy/__init__.py'>:Module (NoMethodError)
Did you mean?  display
        from /home/affinity/vendor/bundle/ruby/3.2.0/gems/ruby-spacy-0.1.5.4/lib/ruby-spacy.rb:30:in `<module:Spacy>'
        from /home/affinity/vendor/bundle/ruby/3.2.0/gems/ruby-spacy-0.1.5.4/lib/ruby-spacy.rb:9:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        ...
```

**Comment by yohasebe** [comment]
Thanks for the info. I'll look into it.

For the time being, ruby-spacy (0.2.1, gem not released yet) checks the spaCy version and if it is 3.7 or greater, it disables the visualization features that need `displacy`.
